// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooxnyaqafspuyqfzociw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9veG55YXFhZnNwdXlxZnpvY2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0MDYxNzQsImV4cCI6MjA4Njk4MjE3NH0.DSmMx9ssKB_6gx6eOEdeB43JjAngVd2rhQbpva9pa0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
